services:
  gateway:
    build: gateway
    image: sww-gateway
    container_name: sww-gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SWW_SERVER_URL=http://server:9090

  server:
    build: server
    image: sww-server
    container_name: sww-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/sww
      - SPRING_DATASOURCE_USERNAME=sww
      - SPRING_DATASOURCE_PASSWORD=sww

  db:
    image: postgres:16.1
    container_name: sww-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=sww
      - POSTGRES_USER=sww
      - POSTGRES_DB=sww
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10